// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PFA_Project.Models;

public partial class TblExpentidure
{
    public int ExpentidureId { get; set; }

    public int? Amount { get; set; }

    public string Details { get; set; }

    public int? FundTypeId { get; set; }
}